---
name: YAML Lint Validation

"on":
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.x'
    outputs:
      yamllint_success:
        description: "Did yamllint succeed?"
        value: ${{ jobs.yamllint.outputs.yamllint_success }}

jobs:
  yamllint:
    name: YAML Validation
    runs-on: ubuntu-latest
    outputs:
      yamllint_success: ${{ steps.yamllint.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-yamllint
          restore-keys: |
            ${{ runner.os }}-pip-yamllint-
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint and capture output
        id: yamllint
        run: |
          yamllint . 2>&1 | tee yamllint-output.txt
          STATUS=${PIPESTATUS[0]}
          if [ $STATUS -eq 0 ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload yamllint results
        uses: actions/upload-artifact@v4
        with:
          name: yamllint-results
          path: yamllint-output.txt
          if-no-files-found: warn

      - name: Fail job if yamllint found issues
        if: steps.yamllint.outputs.success == 'false'
        run: |
          echo "❌ yamllint found issues in YAML files"
          exit 1
